### ISSUE TITLE
weatherTimestamp not getting calculated correctly by main_fwx

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-rfc-climate-obs#48]
the fire weather stations weather time stamps are being recorded as 2023112721, 2023112722, 2023112799.  The one that is 2023112799 should be 2023112723.

Figure out what's going on with this and correct the script, then retroactively generate new data.

**Comment by franTarkenton** [comment]
the timestamps have a correction factor applied to them of -1 hour.  The math to calculate the time was using a datetime integer.  When the time recorded says 00 was subtracting 1 resulting in 99.  Resolves by converting to a datetime and doing  the math using timedelta.

Should be fixed for subsequent runs.  Need to circle back and resolve for past runs.

**Comment by KYSIEMENS** [comment]
Ran script to cycle through all existing fwx files and convert timestamps with hour '99' back to '23'.
